### ISSUE TITLE
Incompatibility with Chunk Pregenerator

### ISSUE THREAD

**Issue by HighQGithub** [TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs#14]
**(Forge 1.12.2)**
Generating a world with chunk pregenerator will result in all biomes being tagged as plains

**How to reproduce:**

- Start a multiplayer server with chunk pregenerator and RoughlyEnoughIDs
- Start the server and start pregeneration before a player logs on
- after a few chunks have pregenerated, log into the multiplayer world and check the F3 menu to see the biome tags (All biomes should be labelled as plains)

**Comment by HighQGithub** [comment]
I fixed the issue by updating from RTG 1.12.2 Preview to RTG Unofficial 1.0.2, however, I would need to do more testing to see if this error is still reproducible on Vanilla clients and servers. I would also recommend checking how REI handles chunk pregeneration tasks to avoid potential conflicts in the future.

Thanks for the good work guys! Really appreciate the work you guys are doing here! The mod seems to be significantly less buggy in contrast to other mods like Just Enough IDs and Not Enough IDs.

**Comment by aking4125** [comment]
This bug occurs without RTG however. Any dimension in our server will result in a plains biome being generated instead. 

Imagine wandering the Nether and seeing Grass and Sheep around Lol.

For the time being, we have to use the generation feature from Forge. Which is extremely slow but it does work.

**Comment by GrouwBer** [comment]
still not working with Chunk Pregenerator

**Comment by BinBashBanana** [comment]
I just thought I'd link the original issue, which has some more info on the bug: https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/42
