### ISSUE TITLE
Minecraft fails to start with REID

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs#18]
Hello,

Switching out my JEID and NEID for this mod makes minecraft unable to be launched. I am one of the people who has the issue of world generating empty chunks with NEID and JEID, so this mod would be a very welcome fix.

here is the crash log;
https://pastebin.com/ZuTmCVWF

**Comment by ACGaming** [comment]
Seems like you have mods with different bundled versions of Mixin. You can try if [this mod](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility) helps.

**Comment by ErnestoPeroPezzi** [comment]
You are entirely correct, had forgotten what a mixin incompabilty crash looked like. After a bit of tinkering, I got it to stop. Loading in now :)
