### ISSUE TITLE
Fix the Currently Supporting part of the mod's description.

### ISSUE THREAD

**Issue by MagmaBro123** [TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs#2]
Title. Are these even on Curse at all? If not, may wanna remove these invalid links.

![image](https://user-images.githubusercontent.com/51277766/178159204-487a3526-9b96-4b70-969d-d1d520a2b6fc.png)

**Comment by Lylythii** [comment]
Please don't open issues that have nothing to do with the mod.
The description is accurate.
