### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by HolyFuckItsAMEME** [TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs#26]
Completely confused, as this mod worked with every mod I had installed beforehand. I am unsure what I have done wrong.

Here's the log from startup, even though the game crashes entirely before it can.
[latest.log](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/files/12780540/latest.log)

**Comment by ACGaming** [comment]
Looks like it‘s connected to SecurityCraft?

**Comment by HolyFuckItsAMEME** [comment]
Interesting. I wonder why. Again, REID worked just fine with everything I had installed beforehand. So strange that SC is now incompatible, even without changes.
Thanks. I'll test to see if removing SC helps, or maybe downloading a different version of it

**Comment by HolyFuckItsAMEME** [comment]
I did some testing on my own (very basic, literally just adding a few mods at a time to see what works and what doesn't) and I did find the incompatibility. It was the mod LootingVI. I removed it and everything loaded perfectly again.
