### ISSUE TITLE
Is this compatible with Cubic Chunks now, or is it still in its infancy? 

### ISSUE THREAD

**Issue by Grausiga** [TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs#3]
I have created a server with original JEID and we have cubic chunks, apparently JEID is incompatible with Cubic chunks, so it will soon start to corrupt our 10000h+ old world....

Is your mod ready to be used? Is the main release that which has Cubic Chunks support? Can your mod replace JEID like it says on curse? 

Thanks for your work and I'm waiting eagerly for your response!

**Comment by Lylythii** [comment]
To start. Yes, migrating from JEID to REID is perfectly fine to do. (back-up your world if you're uneasy about this)
The build on CurseForge doesn't currently support Cubic Chunks *yet*, however...

If you want to test out compatibility, you can try compiling *this* branch; https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/tree/CubicChunksSupport

It should work, blocks exceeding vanilla's limit don't seem to corrupt in chunks, but more testing could go into checking *if* it *can be broken*.

Quote;
> I tested to confirm it was working, but not to see if I could break it
> I confirmed the data saved and loaded, and that a 16x16x16 chunk could have more than the vanilla number of unique blocks

I'll look into getting it released on CurseForge soon.

**Comment by samuelvergeiner** [comment]
Thank you so much for your answer, I will certainly try this out extensively!

I will post my results here.

Again, thank you for creating this

**Comment by Mysticpasta1** [comment]
The cubic chunks team has noticed this :D I thought I'd let you know that if you have discord the team I believe will be willing to help you with CC compat

**Comment by Mysticpasta1** [comment]
https://discord.gg/W3jkzRAAeJ

**Comment by Barteks2x** [comment]
This should be enough to get it working. Ideally i would give you some less hacky way to hook into the mod that I would have some manageable way to keep compatibility with, so i will try to make something. This won't go into actual API jar because it's very specific to the needs of this mod.

**Comment by Lylythii** [comment]
Once approved by CurseForge, CubicChunks should be compatible with this build; https://www.curseforge.com/minecraft/mc-mods/reid/files/4205759

We can then consider less hacky methods for future versions.
