### ISSUE TITLE
CM3 Preview break again in 2.0.8

### ISSUE THREAD

**Issue by zeng-github01** [TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs#36]
as the title says

**Comment by jchung01** [comment]
Looks like the mod id is wrong [here](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/blob/master/src/main/java/org/dimdev/jeid/mixin/init/JEIDMixinLoader.java#L32). Should be `compactmachines3`. I'll be making a PR soon that refactors a lot of the mod's code, so I'll include it in there, or you can just make a simple PR to fix it.
