### ISSUE TITLE
Crash with Aether II

### ISSUE THREAD

**Issue by Robolightning** [TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs#38]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/world/chunk/Chunk

Minecraft: 1.12.2
Forge: 14.23.5.2860
[RoughlyEnoughIDs: 2.0.8](https://www.curseforge.com/minecraft/mc-mods/reid/files/5143492)

[Mixinbooter: 9.1](https://www.curseforge.com/minecraft/mc-mods/mixin-booter/files/5079135)
[Aether II: 0.3.0+build411-universal](https://www.curseforge.com/minecraft/mc-mods/aether-ii/files/2960610)

logs:
[crash-2024-03-06_01.04.48-client.txt](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/files/14502022/crash-2024-03-06_01.04.48-client.txt)
[latest.log](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/files/14502016/latest.log)
[debug.log](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/files/14502015/debug.log)
[launcher_log.txt](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/files/14502047/launcher_log.txt)

**Comment by zeng-github01** [comment]
Looks like this is a compatibility issue related to [Phosphor](https://www.curseforge.com/minecraft/mc-mods/phosphor-forge)

Its source code is no longer available to the public, and I recommend you turn off support for it in The Aether II's configuration. This problem can be solved

**Comment by zeng-github01** [comment]
@Robolightning I have submitted a patch, and when this patch is applied, please replace "Phosphor" with "Hesperus". This will fix compatibility with this one

**Comment by zeng-github01** [comment]
> Better yet, use [this Aether II fork](https://www.curseforge.com/minecraft/mc-mods/the-aether-ii-phosphor-not-included) instead and use the lighting engine of your choosing between Hesperus or Alfheim. Although I think the OP already got the message in [CleanroomMC/MixinBooter#73](https://github.com/CleanroomMC/MixinBooter/issues/73) for this particular issue.

It seems that this issue can be closed directly with the unplanned option

**Comment by zeng-github01** [comment]
@jchung01 Oh, I have a mod that I want to port to 1.16.5, but I can't port it completely. Every time I try it crashes. Can you help me take a look?
