### ISSUE TITLE
Possible fix for Chunk Pregenerator problem

### ISSUE THREAD

**Issue by NostalgicLorikeet** [TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs#40]
Somebody appeared to fix the problem with CPG generating only plains biomes a few years ago in this comment [here](https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/42#issuecomment-520286560). I checked the class that was modified and it appears to be the same in REID and JEID. Any chance this could be looked into?

**Comment by jchung01** [comment]
I also saw this comment, I was planning on looking into it after my PR got merged, just to isolate any potential issues that may arise with implementing this.
