### ISSUE TITLE
Incompatibility with More Planets Mod

### ISSUE THREAD

**Issue by TLinkan** [TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs#42]
The "Fronos River" biome gets overwritten with a different biome when REID (or even JEID) is installed. It becomes even more apparent when Biomes O Plenty is in use. The TellMe mod is used in these screenshots to show the error.

Mods tested for this:
More-Planets-1.12.2-2.3.3-GC4.0.6
BiomesOPlenty-1.12.2-7.0.1.2445-universal
RoughlyEnoughIDs-2.0.8

No REID/No BoP
![316398815-e71f3603-64e3-4711-883e-4bcc600b94fc](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/assets/66501970/f1f75574-0639-4580-9a88-97fb9abf43d4)

REID/No BoP
![316400505-b0b494cf-df15-44bc-949e-a4a2de10eaac](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/assets/66501970/19806e08-23c7-424b-b94d-530f2ef5085d)

REID/BoP
![316402524-9bf3546f-d097-400d-b5c2-17dc1c9cbc28](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/assets/66501970/b1ebb10e-613d-423d-91d2-319be0509695)

**Comment by jchung01** [comment]
Can you see if this build fixes it? (Make sure to unzip) 
[RoughlyEnoughIDs-2.0.8.jar.zip](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/files/14766563/RoughlyEnoughIDs-2.0.8.jar.zip)

**Comment by TLinkan** [comment]
> Can you see if this build fixes it? (Make sure to unzip) [RoughlyEnoughIDs-2.0.8.jar.zip](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/files/14766563/RoughlyEnoughIDs-2.0.8.jar.zip)

Yep, that definitely fixes things up! Tysm! 
![2024-03-26_23 21 35](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/assets/66501970/c8f15f6f-2452-4a1a-8014-00f346efc45b)

**Comment by jchung01** [comment]
Got it, will submit PR later after the current one is accepted.

**Comment by Lylythii** [comment]
> Got it, will submit PR later after the current one is accepted.

[Consider it done](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/commit/faf5619fbd7f0105ff410797af03b87f23311b87).
