### ISSUE TITLE
RTGU-Create world crash

### ISSUE THREAD

**Issue by al-wei** [TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs#46]
RoughlyEnoughIDs-2.1.0
RTGU-1.12.2-1.1.0

https://mclo.gs/k5meB9z
https://gist.github.com/al-wei/1912d533e3ca3be43d440f08b12e0d02

**Comment by jchung01** [comment]
Ah, the one mod I forgot to test... Luckily a simple fix.
