### ISSUE TITLE
Crash while connecting to world

### ISSUE THREAD

**Issue by Robolightning** [TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs#52]
After installation, the minecraft mod freezes when entering a new world. Everything works fine when using NEID. The problem occurs when trying to remove it
[launcher_log.txt](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/files/15028416/launcher_log.txt)
[latest.log](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/files/15028419/latest.log)

**Comment by zeng-github01** [comment]
> After installation, the minecraft mod freezes when entering a new world. Everything works fine when using NEID. The problem occurs when trying to remove it [launcher_log.txt](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/files/15028416/launcher_log.txt) [latest.log](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/files/15028419/latest.log)

Please use REID v2.1.1
