### ISSUE TITLE
Does not work with IC2

### ISSUE THREAD

**Issue by AshleighTheCutie** [TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs#62]
As the title says. JEID has the void chunks issue, and this breaks the pack due to this: https://mclo.gs/B8BLe2v

The server also has a similar error.

**Comment by jchung01** [comment]
Phosphor is not compatible with MixinBooter because Phosphor ships an older version of the same library, and thus is not compatible with any mods that depend on MixinBooter (like this mod). Please use [Hesperus](https://www.curseforge.com/minecraft/mc-mods/hesperus) or [Alfheim](https://www.curseforge.com/minecraft/mc-mods/alfheim-lighting-engine) instead of Phosphor.

**Comment by AshleighTheCutie** [comment]
The client opens now, but the server is still broken: 
[crash-2024-07-08_14.03.17-server.txt](https://github.com/user-attachments/files/16134508/crash-2024-07-08_14.03.17-server.txt)

**Comment by jchung01** [comment]
1) Was the world originally created with NEID?
2) Can you successfully load into a new world?

**Comment by AshleighTheCutie** [comment]
1. Yes, it was. The mod should still be present
2. I am not sure. Even if I can, resetting is not an option. 1800 hours is a long time to lose.

**Comment by AshleighTheCutie** [comment]
Alright, the server runs now. However, the client has a new crash!

https://mclo.gs/A4KCy1f

**Comment by jchung01** [comment]
I have no idea what's happening in that crash. Do you have a backup of your world that was **before you added REID**? Use that backup, and load **only with REID, not NEID**. If you load the world with both mods installed, you will most likely experience weird world holes that are permanent.

**Comment by AshleighTheCutie** [comment]
I do not, no. NEID was added at first, then JEID when I hit the dimensions limit. And that was at... maybe the 200 hour mark?

The crash was partially fixed by removing Plants, but now I can't join the server without getting this:
![image](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/assets/35613156/d53382be-b60f-48e4-b2d3-905ba5b7fd8f)
And no, the server log has *nothing*.

And entering a brand-new single-player world results in [this](https://github.com/user-attachments/files/16137686/latest.log).

**Comment by AshleighTheCutie** [comment]
I cannot disable NEID, doing so bricks both the server and client. It's 00:33 here, I can mess with this more tomorrow. Is there a Discord server I can join to debug this in? I feel it might have grown into a more involved thing than a single GitHub issue should probably contain...

**Comment by jchung01** [comment]
Can talk more here https://discord.gg/JdthM8qbJ3

**Comment by jchung01** [comment]
Should have been resolved, it was an issue of having both NEID and REID installed. Having both seems to cause voided chunks/world "holes", if not worse side-effects, so a check in the future to prevent users from having both mods installed will be a good idea.
