### ISSUE TITLE
Question about RTG compat implementation

### ISSUE THREAD

**Issue by han-thony** [TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs#63]
How is RTG compatibility implemented? I went through all @jchung01's commits but couldn't figure it out. It seems like implementing "IModSupportsJEID" just causes RTG's chunk generator to bypass the REID injection. Is there compatibility implemented on the RTG side? I couldn't find it in their repo. I'm curious because I'm interested in adding compatibility for similar mods.

**Comment by jchung01** [comment]
> It seems like implementing "IModSupportsJEID" just causes RTG's chunk generator to bypass the REID injection.

This is correct, previous versions explicitly checked for RTG's `ChunkGeneratorRTG`, but this does the same thing.

Compatibility is explicitly provided on RTG's side, but only from forks of the mod. The forks that I'm aware of that do this are [RTG Unofficial](https://www.curseforge.com/minecraft/mc-mods/realistic-terrain-generation-unofficial) (compat [impl](https://github.com/juraj-hrivnak/RTGUnofficial/commit/8672d02e3f3675597c2c857a8a7ca05dfde67d53)) and [RTG+](https://www.curseforge.com/minecraft/mc-mods/realistic-terrain-generation-plus) (compat [impl](https://github.com/Zeno410/Realistic-Terrain-Generation-Plus/commit/cad68cd0dcb397823d08d9cb17383e4dc612676f)).

Generally, any mods that implement `IChunkGenerator` shouldn't need explicit compatibility as the only thing that needs to be done is set REID's biome array, which is already done in [`MixinChunkProviderServer`](https://github.com/TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs/blob/master/src/main/java/org/dimdev/jeid/mixin/core/world/MixinChunkProviderServer.java) after the mod's `IChunkGenerator#generateChunk` is called. RTG seems to be a special case as it handles its biome gen (specifically river gen) in a unique way that breaks if REID's injection is run. I'm curious to know which mods you have in mind, as REID should be compatible with most modded chunk generators as is.

**Comment by han-thony** [comment]
That makes sense, thank you for the response.

I was specifically interested in OTG for 1.12.2. Based on the code I've looked at, I think it's very possible OTG would work out of the box but on the OTG discord server the developers consistently say JEID type mods aren't compatible. 

I haven't tested them together or investigated closely yet but if you're already familiar with how REID and OTG interact that would be helpful.

**Comment by jchung01** [comment]
I believe @Mysticpasta1 has a working build of OTG that's compatible with REID, as mentioned in #5. You would need to build the jar yourself off of PG85/OpenTerrainGenerator#1000 though. Last time I checked there didn't seem to be any issues with it, but I didn't test throughly.
