### ISSUE TITLE
REID maybe break AE2 Extend Life

### ISSUE THREAD

**Issue by zeng-github01** [TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs#69]
[crash-2024-11-05_21.48.20-client.txt](https://github.com/user-attachments/files/17633486/crash-2024-11-05_21.48.20-client.txt)

This bug causes the wireless terminal to randomly force close, because OutOfRange

**Comment by jchung01** [comment]
The only place I see where a null pointer exception can occur in `NetHandlerPlayClient#handleEntityEffect()` is if the world is null, which is not changed by REID. The crash report doesn't look correlated to your issue though, so are there any other crash reports?

**Comment by zeng-github01** [comment]
> The only place I see where a null pointer exception can occur in `NetHandlerPlayClient#handleEntityEffect()` is if the world is null, which is not changed by REID. The crash report doesn't look correlated to your issue though, so are there any other crash reports?

Not yet. To be honest, this kind of error in AE is very strange.
