### ISSUE TITLE
World painter and /setbiome command don't work

### ISSUE THREAD

**Issue by velyn01** [TerraFirmaCraft-The-Final-Frontier/RoughlyEnoughIDs#9]
REID worlds don't load with World Painter program and the /setbiome command from world edit doesn't work either.

**Comment by velyn01** [comment]
world edit can't work with new IDs too

**Comment by ACGaming** [comment]
These programs were made to utilize the default ID system in Minecraft 1.12. Since REID implements the modern ID system introduced in 1.13+, the respective functionality is incompatible and not fixable from our side.
